### ISSUE TITLE
Ensure Inter font family is loading

### ISSUE THREAD

**Issue by petrinkae** [transja/styleguide.transjournalists.org#11]
Extremely nitpicky and probably not necessary, but if we could match the main site nav sizing to the style guide nav sizing, that would be a nice tweak!
<img width="1411" alt="Screen Shot 2023-08-25 at 9 52 28 AM" src="https://github.com/transja/styleguide.transjournalists.org/assets/15100923/2e19b13e-4e72-4675-bff0-6dd63bcf2444">
<img width="1431" alt="Screen Shot 2023-08-25 at 9 52 21 AM" src="https://github.com/transja/styleguide.transjournalists.org/assets/15100923/1560f7ba-0aee-4249-87f7-63e686224978">

**Comment by aendra-rininsland** [comment]
It's possible you're at different zoom levels, it looks the same to me. That said, the fonts aren't pulling in yet.
